#!/usr/bin/env python3
"""Generate *_p.asm (HLCALL/IXCALL dispatch) and *_np.asm (direct CALL) from ; process sources."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PROC = re.compile(r"^\s*;\s*process\s*$", re.I)


def transform_line(line: str) -> tuple[str, str] | None:
    s = line.strip()
    if not s:
        return None
    parts = s.split()
    if len(parts) >= 2 and parts[0] in ("HLCALL", "IXCALL"):
        op, param = parts[0], parts[1]
        reg = op[:2]  # HL or IX
        p = (
            f"\tld\t{reg}, {param}\n\tcall\t{op}\n",
            f"\tcall\t{param}\n",
        )
        return p
    return None


def process_file(src: Path) -> None:
    text = src.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines(keepends=True)
    if not lines or not PROC.match(lines[0].rstrip("\r\n")):
        return

    p_out: list[str] = []
    np_out: list[str] = []
    hdr = "; do not edit this file, it has been automatically generated.\n"
    p_out.append(hdr)
    np_out.append(hdr)

    for line in lines[1:]:
        t = transform_line(line)
        if t is None:
            p_out.append(line)
            np_out.append(line)
        else:
            p_line, np_line = t
            p_out.append(p_line)
            np_out.append(np_line)

    stem = src.stem
    (ROOT / f"{stem}_p.asm").write_text("".join(p_out), encoding="utf-8")
    (ROOT / f"{stem}_np.asm").write_text("".join(np_out), encoding="utf-8")


def main() -> None:
    for p in sorted(ROOT.glob("*.asm")):
        name = p.name
        if name.endswith("_p.asm") or name.endswith("_np.asm"):
            continue
        if name == "getmountpoint.asm":
            continue
        process_file(p)


if __name__ == "__main__":
    main()
